name: Generate Snake

on:
  schedule: # every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: KhalilBensaha
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
